### ISSUE TITLE
Latest main does not show anything in RViz when running examples

### ISSUE THREAD

**Issue by glpuga** [Ekumen-OS/beluga#123]
## Required info
- Version or commit hash:
  - ea3375016e86264a3ef3785bf62619c3becdaab8

## Steps to reproduce issue

- Get in container
- Run  `cd /ws && colcon build && source install/setup.bash && ros2 launch beluga_example example_rosbag_launch.py`

## Expected behavior

Older versions showed the map and sensor data in RViz. This is a capture from running 00295e8353646973741af17659684b9b4d51e846 :

![Screenshot from 2023-02-26 17-04-35](https://user-images.githubusercontent.com/17802342/221434421-110e29de-e477-4a66-b52c-9728110149c3.png)

## Actual behavior

Current behavior displays this:

![Screenshot from 2023-02-26 17-05-55](https://user-images.githubusercontent.com/17802342/221434456-44509d52-efdf-4c0d-a194-dd0370b44ee6.png)

## Additional information

---

**Comment by nahueespinosa** [comment]
Linking the Ubuntu bug report for future reference: https://bugs.launchpad.net/ubuntu/+source/mesa/+bug/2004649
