### ISSUE TITLE
Document relevant mixin usage patterns

### ISSUE THREAD

**Issue by glpuga** [Ekumen-OS/beluga#129]
## Description

The last few weeks have been rich in design proposals for problems we're likely to encounter again.  Since we are

A few of these are probably worth keeping around as part of the permanent documentation, for

- Design documentation for third-parties.
- New developer onboarding.
- Archival. Lots of good godbolt examples that should not be lost and can potentially be reused. 

## Definition of done

- [ ] Define storage place. Linkable Doxygen docs, markdown documentation in repository, other?
- [ ] Define template. The pattern information as structured in the GoF book can be a start point: https://en.wikipedia.org/wiki/Software_design_pattern#Documentation
- [ ] Document general C++ mixin pattern as used in Ciabatta.
- [ ] Document Ivan's additive modules proposal described [here](https://github.com/ekumenlabs/beluga/pull/119#issuecomment-1452420709).
- [ ] Document Nahuel's `std::visit` usage to create a filter factory proposed [here](https://github.com/ekumenlabs/beluga/issues/118#issuecomment-1445167320) and with a larger example in [here](https://github.com/ekumenlabs/beluga/issues/118#issuecomment-1445232575).

**Comment by hidmic** [comment]
Considering we are moving away from mixins, I'm inclined to close this ticket. 

@glpuga please do if you agree.
