### ISSUE TITLE
Use LAMBKIN for performance benchmarking

### ISSUE THREAD

**Issue by hidmic** [Ekumen-OS/beluga#163]
## Description

Once we are past #85, we will need extensive performance benchmarking to show `beluga_amcl` is indeed as good if not better than `nav2_amcl`. While we could extend #117 to suite all our needs, LAMBKIN may already provide the necessary infrastructure for it -- particularly once https://github.com/ekumenlabs/lambkin/pull/35 lands. 

## Definition of done

- [x] Define benchmarks, w.r.t.: 
   - Input data
   - Particle filter setup
   - Performance metrics
- [x] Implement benchmarks using LAMBKIN 
    - LAMBKIN may require extension
- [ ] Publish benchmark reports

**Comment by hidmic** [comment]
A substantial amount of work was pursued by @serraramiro1 already. I'll push it past the finish line.

**Comment by hidmic** [comment]
We have identified a number of additional datasets we can use for this:

- the [Willow Garage](https://google-cartographer-ros.readthedocs.io/en/latest/data.html#pr2-willow-garage) dataset;
- the [TorWIC](https://github.com/Viky397/TorWICDataset) dataset;
- the [OpenLORIS](https://lifelong-robotic-vision.github.io/dataset/scene.html) dataset.

In addition to the [Magazino](https://google-cartographer-ros.readthedocs.io/en/latest/data.html#magazino) dataset, the MARS dataset, the TUM dataset, and the Rawseeds dataset. CC @glpuga.

**Comment by glpuga** [comment]
- [Hilti Challenge 2022 dataset](https://hilti-challenge.com/dataset-2022.html)
- MARS???
- [Malaga 2009](https://www.mrpt.org/malaga_dataset_2009)
- [NCTL](https://robots.engin.umich.edu/nclt/), through [nclt2ros](https://github.com/bierschi/nclt2ros) ?
- [OpenLORIS](https://lifelong-robotic-vision.github.io/dataset/scene.html) 
- [Rawseeds dataset](http://www.rawseeds.org/home/category/benchmarking-toolkit/datasets/)
- ["TUM"](https://www.mrpt.org/Collection_of_Kinect_RGBD_datasets_with_ground_truth_CVPR_TUM_2011) (only a subset)
- [Willow Garage](https://google-cartographer-ros.readthedocs.io/en/latest/data.html#pr2-willow-garage)

**Comment by hidmic** [comment]
This has materialized in https://github.com/Ekumen-OS/lambkin/pull/93, which will be relocated to this repository with https://github.com/Ekumen-OS/beluga/pull/415 once it consolidates. Pending issues are LAMBKIN specific and we can track them there. Closing as done.
