### ISSUE TITLE
Select public datasets to benchmark Beluga

### ISSUE THREAD

**Issue by nahueespinosa** [Ekumen-OS/beluga#166]
## Description
As part of #163, we need to define which input datasets to use for benchmarking. We should aim for selecting a subset of the available datasets that represent different localization conditions. The nature of those conditions remains to be defined, but in principle:
- Environments could be classified by their symmetry, indoor/outdoor, dynamic/static, etc.
- Sensor data could have different characteristics (i.e. precision, resolution, publish rate?).
- Ground-truth data might be available or not (for our application this is a must-have).

Regarding sensor configuration, we currently support 2D LIDAR + odometry.

The common format will most likely need to be a ROS 2 bag, so some preprocessing scripts will be needed.

## Definition of done
- [ ] We have a list of datasets pre-processed and ready to use with LAMBKIN.

## Additional considerations
We have collected public datasets in the past (although the pre-processing was done with ROS 1 in mind), see https://github.com/ekumenlabs/RnD/issues/5.

We should also check out new collections, for example: https://github.com/mint-lab/awesome-robotics-datasets.

**Comment by hidmic** [comment]
I think we can call this done, as generic as the description is.
