### ISSUE TITLE
Force update when there is no movement

### ISSUE THREAD

**Issue by olmerg** [Ekumen-OS/beluga#184]
[in the parity amcl ](https://github.com/Ekumen-OS/beluga/issues/85) this is implemented though a service `request_nomotion_update`. Although in nav2_amcl is just a flag, in beluga it is required to modify the policies like [resample_on_motion_policy](https://github.com/Ekumen-OS/beluga/blob/main/beluga/include/beluga/resampling_policies/resample_on_motion_policy.hpp)

## Definition of done

- [x] Define the way to be implemented
- [x]  implement the service in beluga_amcl
- [x] modify the policies in beluga

**Comment by stwirth** [comment]
This feature is useful to refine a manually set pose (via `/initialpose`), see https://github.com/ros-planning/navigation/pull/1226.

**Comment by nahueespinosa** [comment]
Thanks for the context! When I commented a few months ago, Beluga was updating the filter motion and sensor models all the time, so a manual update was not required for the robot to re-localize when the initial pose was published.

In the current version, after #233, which makes resampling policies much more similar to AMCL, this makes a lot of sense.

**Comment by hidmic** [comment]
Solved!
