### ISSUE TITLE
Building API documentation should be disabled when Doxygen is not installed.

### ISSUE THREAD

**Issue by stwirth** [Ekumen-OS/beluga#226]
### Bug description
_A clear and concise description of what the bug is._

```
==> Processing plain cmake package: 'beluga'
==> cmake /mypath/src/beluga/beluga -DCMAKE_INSTALL_PREFIX=/mypath/devel_isolated/beluga -G Unix Makefiles in '/mypath/build_isolated/beluga/devel'
-- Build testing enabled.
-- Build API documentation enabled.
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /mypath/build_isolated/beluga/devel
==> make -j4 -l4 in '/mypath/build_isolated/beluga/devel'
Scanning dependencies of target beluga_docs
Scanning dependencies of target gtest
Scanning dependencies of target clang_tidy_findable
Scanning dependencies of target benchmark_beluga
[  2%] Generating API documentation with Doxygen
/bin/sh: 1: DOXYGEN_EXECUTABLE-NOTFOUND: not found
make[2]: *** [docs/CMakeFiles/beluga_docs.dir/build.make:58: docs/CMakeFiles/beluga_docs] Error 127
make[1]: *** [CMakeFiles/Makefile2:1195: docs/CMakeFiles/beluga_docs.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Platform (please complete the following information):**
 - OS: Ubuntu Focal, ROS noetic
 - `Beluga` version: ed7dfe38bcab566a900b636378e7dbf05981120a

### How to reproduce
_List steps to reproduce the issue:_
1. make sure doxygen is not installed
2. clone into catkin_ws/src
3. catkin_make_isolated

_Code snippets or minimal examples are always helpful, if not necessary._

**Expected behavior**
_A clear and concise description of what you expected to happen._
No failures.

**Actual behavior**
_A clear and concise description of what actually happened._
see above

### Additional context
_Any other information you think could be meaningful to this issue._

**Comment by hidmic** [comment]
Also, `doxygen` should be listed as `doc_depend`.
