### ISSUE TITLE
Repo description does not mention ROS 1

### ISSUE THREAD

**Issue by glpuga** [Ekumen-OS/beluga#246]
### Issue description

The repo description mentions the project as a general solution for MCL only for ROS 2.

### Additional context

![Screenshot from 2023-07-12 16-26-24](https://github.com/Ekumen-OS/beluga/assets/17802342/dd7c91b6-c34f-4ccb-a505-27d551d3465e)

**Comment by nahueespinosa** [comment]
Description updated!
