### ISSUE TITLE
Clustering for pose estimation

### ISSUE THREAD

**Issue by hidmic** [Ekumen-OS/beluga#258]
### Feature description

Connected to https://github.com/Ekumen-OS/beluga/discussions/172. Good ol' AMCL computes sampled mean and covariance from particle clusters, whereas Beluga AMCL computes sampled mean and covariance for the entire posterior particle cloud. Regardless of any arguments in favor or against either approach, Beluga AMCL should offer the choice. We need another estimation mixin.

**Comment by glpuga** [comment]
Do we know any paper/source for the implementation of this by AMCL?

**Comment by hidmic** [comment]
Not that I know of. That said, the idea of clustering has been floating around for a long while e.g. https://arxiv.org/pdf/cs/0204044.pdf.

**Comment by hidmic** [comment]
Addressed as of #275.
