### ISSUE TITLE
Matplotlib is broken in Humble image, probably others

### ISSUE THREAD

**Issue by glpuga** [Ekumen-OS/beluga#262]
### Bug description

When trying ot run the benchmarking scripts to plot data, this error happens:

![Screenshot from 2023-10-19 14-16-04](https://github.com/Ekumen-OS/beluga/assets/17802342/d0283aad-97f0-4192-bcdc-9df907706dfe)

This is a reported issue in Matplotlib: https://github.com/matplotlib/matplotlib/issues/26827

It's important to notice that this issue should affect matplotlib 3.8.0. While the official Ubuntu `python3-package` that is the declared dependency of `beluga_benchmark` installs 3.5.1, a second installation of matplotlib is added to the system through pip when installing `evo==1.21.0` in the docker file, which brings `matplotlib==3.8.0`.

As of now, the only workaround this to manually do:
```
sudo pip3 install matplotlib==3.7.3
```

**Platform (please complete the following information):**
 - OS: Development docker for Humble
 - `Beluga` version: 31445270321482c72dc8a7608385a0682880151b

### How to reproduce
_List steps to reproduce the issue:_
1. Start the Humble docker container
2. Start a python3 terminal
3. Type `import matplotlib.pyplot as plt`

**Expected behavior**

No error output.

**Actual behavior**

The error output shown above is printed.

**Comment by hidmic** [comment]
>  a second installation of matplotlib is added to the system through pip when installing evo==1.21.0 in the docker file, which brings matplotlib==3.8.0.

For the time being, let's just peg `matplotlib` to `~3.7.0` in that same Dockerfile and move on.

**Comment by hidmic** [comment]
Closing for the same reasons #263 was closed.
