### ISSUE TITLE
Write tutorial on extending Beluga 

### ISSUE THREAD

**Issue by hidmic** [Ekumen-OS/beluga#306]
### Feature description

Precisely what the title says. Despite the fact extensibility is one of Beluga's major selling points, we have zero documentation on how one is supposed to do that. Any canonical dynamic system (particle, pendulum) could be used as a basis to demonstrate how algorithms and models are implemented in Beluga.

Make sure to at least cover:

- [x] A sensor model implementation
- [x] A motion model implementation
- [ ] A sampling method implementation
- [x] An estimate method implementation

**Comment by hidmic** [comment]
@nahueespinosa is it time to circle back to #358 already?

**Comment by nahueespinosa** [comment]
@hidmic I have no bandwidth for this, but yes, I guess so.
