### ISSUE TITLE
Add conversion script from `pbstream` to NDT map

### ISSUE THREAD

**Issue by serraramiro1** [Ekumen-OS/beluga#348]
### Feature description

Basically what the title says.
This'll unblock #316 .

**Comment by nahueespinosa** [comment]
I've been looking into this and noticed that the serialized pose graph does not include raw range data. What it does include are the submaps. Could you say more about what you had in mind for this task?

**Comment by nahueespinosa** [comment]
Here are some insights (thanks @serraramiro1 for the clarification!):

- The existing [`conversion_utils.py`](https://github.com/Ekumen-OS/beluga/blob/71d3f0cae0588ce2fed1beb847999bf08e2fcf69/beluga_ros/src/beluga_ros/conversion_utils.py) library provides tools for converting any point cloud into an NDT map in HDF5 format.
- The goal here is to aggregate the [`filtered_gravity_aligned_point_cloud`](https://github.com/cartographer-project/cartographer/blob/877157a0d91788a7700221d87232d412cb3c1ef4/cartographer/mapping/proto/trajectory_node_data.proto#L27) stored in each trajectory node of a serialized pose graph to generate a point cloud, and use that point cloud to generate the NDT map.
- There is a tool that can run through a ROS bag with the trajectory found in a pbstream file to generate a full resolution PLY: https://google-cartographer-ros.readthedocs.io/en/latest/assets_writer.html
- Converting from PLY to NDT is not a bad idea, but there is also value in processing pose graph information without the ROS bag dependency even if that means working with heavily filtered sensor data.
