### ISSUE TITLE
Compare performance between `beluga_amcl` and `nav2_amcl`

### ISSUE THREAD

**Issue by nahueespinosa** [Ekumen-OS/beluga#35]
## Description

Now that we have a functional ROS2 node [`beluga_amcl`](https://github.com/ekumenlabs/beluga/tree/master/beluga_amcl), we should start thinking about a comparison with [`nav2_amcl`](https://github.com/ros-planning/navigation2/tree/main/nav2_amcl). It would be ideal to have a reproducible environment to compare performance and accuracy whenever we want as we improve the software (looking at you [`lambkin`](https://github.com/ekumenlabs/lambkin)).

[`QuickMCL`](https://vorpal.se/posts/2019/apr/07/quickmcl-vs-amcl-performance/) already has done this for the ROS1 case, leaving behind [a repository](https://github.com/VorpalBlade/ros_mcl_performance_test) we could use as reference.

## Definition of Done

- [x] Collect performance and accuracy metrics data from both packages.
- [x] Create a report that explains the methodology and results.

**Comment by SteveMacenski** [comment]
I don't see a discussion here on the actual localization quality / improvements that Beluga could offer which seem important. Are there any metrics on this?

**Comment by hidmic** [comment]
@SteveMacenski there are! But the reports have not been made properly public (because time). Our benchmarking toolkit has to go open source (soon enough) and [`beluga_benchmark`](https://github.com/Ekumen-OS/beluga/tree/main/beluga_benchmark) is due for an update (a merge, actually, with our private, soon public codebase). We are getting there...

**Comment by SteveMacenski** [comment]
OK! Let me know if I can be useful. The things I'm looking for (for reference):
- Generally in the same-ish compute regime as AMCL. I don't think it needs to be a race to the bottom, but within reason
- Equal or better localization quality over several realistic spaces (warehouse, office, etc) over long periods of time
- Shown to resolve AMCL's delocalization jumping issues, or at least the potential path for it in the new framework
- Better default tuning which we never really bothered with in Navigation/Nav2 to date

With that, I'm perfectly happy to dump `nav2_amcl` into its own repository on a deprecation track, add in Beluga as default, and the documentation / tutorials to fit. 

- S

**Comment by hidmic** [comment]
> Equal or better localization quality over several realistic spaces (warehouse, office, etc) over long periods of time

Noted. Warehouses are the trickiest for us right now. We would need a collaborator in that line of business (which we haven't found yet). Speaking of large spaces though, I wonder if any Willow Garage datasets (e.g. the one described [here](https://web.archive.org/web/20151207202459id_/http://cgi.cs.duke.edu/~mac/papers/iros12_sm.pdf)) survived to this day. Do you happen to know @mikeferguson? The ones on https://google-cartographer-ros.readthedocs.io/en/latest/data.html#pr2-willow-garage are gone, and 18 hs x 1600 $m^2$ was pretty decent.

> Shown to resolve AMCL's delocalization jumping issues, or at least the potential path for it in the new framework

This one's perhaps the largest stretch. Posteriors may naturally go multi-modal on a particle filter. Maybe the key here is to do so in a controlled manner if it comes that :thinking: CC @glpuga @nahueespinosa.

**Comment by mikeferguson** [comment]
@hidmic I do not know of anywhere those still exist - perhaps reaching out to some of the authors of Cartographer?

**Comment by SteveMacenski** [comment]
> Warehouses are the trickiest for us right now. 

Let me inquire to see if I can get a dataset or two, no promises though. I have a few that I have private NDA access to, but nothing I can share

**Comment by glpuga** [comment]
> I don't see a discussion here on the actual localization quality / improvements that Beluga could offer which seem important. Are there any metrics on this yet?

@SteveMacenski related to this we just posted the results of a benchmarking campaing validating Beluga AMCl against Nav2 AMCL.

Results summary and commentaries are in the blog post [in our site here](https://www.ekumenlabs.com/blog/posts/big-shoes-to-fill-beluga-performance-report/), and the complete bagfile-by-bagfile results are [in this pdf](https://github.com/Ekumen-OS/beluga/releases/download/2.0.2/Beluga.AMCL.Performance.Benchmarking.Results.v0.1.0.pdf)
