### ISSUE TITLE
Fixed frame not found in Rviz while running example for teleoperation.

### ISSUE THREAD

**Issue by MARIANOCEREDA** [Ekumen-OS/beluga#351]
@hidmic FYI.

### Bug description
When running the teleoperation simulation example ( with ROS2 Humble ), rviz is launched but the fixed frame ( **map** ) is not found. Then, it is not possible to teleoperate.

**Platform (please complete the following information):**
 - Running on docker development container ( as indicated in **GETTING_STARTED.md** )
 - ROS version: Humble / Iron

### How to reproduce
Running in the  **development container with ROS2 Humble**, execute the following ( as mentioned in **GETTING_STARTED.md** ):

```
source /opt/ros/humble/setup.bash
cd /ws
colcon build --symlink-install
source install/setup.bash
ros2 launch beluga_example simulation.launch.xml
```
In a new terminal, run the following.
`ros2 run teleop_twist_keyboard teleop_twist_keyboard`

**Expected behavior**
Be able to teleoperate with `teleop_twist_keyboard` node, and see how the robot moves in rviz UI.

**Actual behavior**
When the keys for teleoperation are pressed, the robot does not move anywhere because the fixed frame ( map ) is not found in rviz.

### Additional context
If the fixed frame is changed to **base**, the teleoperation works, but the map and laser are not visible.
It works fine with ROS Noetic version.

How RVIZ UI looks:
![Untitled](https://github.com/Ekumen-OS/beluga/assets/49108618/7444e8a8-ed23-445a-bb70-38a91c139e07)

**Comment by hidmic** [comment]
This should be fixed now. Beluga AMCL was not broadcasting a map -> odom transform because it was not receiving any laser scans (because of #373).
