### ISSUE TITLE
The "Using Beluga with Nav2" example in the documentation is confusing

### ISSUE THREAD

**Issue by glpuga** [Ekumen-OS/beluga#432]
### Issue description

The "Using Beluga with Nav2" section of the documentation is confusing, because the example swaps an existing beluga  setup for a nav2 one, instead of the other way around, which goes against the narrative and the title of the section right before it.

![image](https://github.com/user-attachments/assets/c95ce83c-3c18-4ec7-ba9a-965f43de823f)

Also, the "as explained in its reference page." at the end of [this section](https://ekumen-os.github.io/beluga/tutorials/nav2-integration.html#explanation) needs a reference link.

### Additional context
_Any other information you think could be meaningful to this issue._

**Comment by hidmic** [comment]
Yeap, I know. I have to wrap up the rewrites for this and the `coming soon!` guides.
