### ISSUE TITLE
Beluga for ROS 1 Noetic

### ISSUE THREAD

**Issue by glpuga** [Ekumen-OS/beluga#95]
## Description

Since most robotic systems in production today are still using ROS 1, and it can be expected that they'll continue to do so for some time, creating a ROS 1 version of Beluga may help with adoption and increase the chances of people trying it in current systems.

## Definition of done

A version of beluga_amcl that can be build and run in ROS 1 Noetic exists.

## Additional considerations

Noetic and ROS 1 are only 2.5 years away from EOL, but since ROS 1 is still being widely used, the amount of immediate users probably compensates for the short life cycle when evaluating this effort.

**Comment by hidmic** [comment]
I've started drafting this, using build system conditionals. It'll take me a while though.
